# Code by Mark Agerton (2017-04)
# 
# This file is simply the information in "DI Desktop Raw Data PLUS.docx", which has save date 2016-03-29 and md5 checksum ff6431ff19845965914bf414f00f4740. 
# The information IS NOT CHANGED with the exception of wrapping commands in a list structure. We use this information to import and format the DI flat-files

# The two lists that are created have column names + types and column names + labels. 
# 1) table_field_types 
# 2) table_field_labels

# ----------------- Notes from DI -------------------

# HPDI Raw Data Version 2:
# PDEN_DESC.ALLOC_PLUS

# OVERVALL NOTE:
#     Proper use of HPDI Raw Data Version 2 requires that almost all queries touching PDEN_DESC reference the ALLOC_PLUS column. When DI Desktop released Texas Allocated Production, the column ALLOC_PLUS was added to the PDEN_DESC table in order to identify an Entity ID’s status in regards to the Texas Allocated dataset. Possible values are:
#     •   Y – Indicates that an Entity ID is an part of the Texas Allocated dataset
#     •   N – Indicates an Entity ID is unallocated Texas oil lease.
#     •   X – All other Entity IDs (including Texas gas wells)
#     If a user wants to query using Texas Allocated data, then only records with an ALLOC_PLUS value of Y or X should be queried. To query using unallocated data, records with an ALLOC_PLUS value of N or X should be used. If this column is not referenced, data and production in Texas will be double counted. 

# PDEN_DESC NOTES:
#     STATE: The state the property is in: 
#     •   In Texas this is well completion level for gas wells and leases for oil wells. 
#     •   In Louisiana, this information is at the well completion level. The volumes are allocated from the reported unit and lease volumes based on factors such as test data and well counts. 
#     •   In Oklahoma, this information is reported on the lease level. It is derived from production reported to a given PUN. 
#     •   In Kansas, this information is on a lease level. 
#     •   In Colorado, production prior to 1999 is allocated to the well level from the lease level. After 1999, all wells were reported on the well level. 
#     •   Other areas are currently reported at the well/completion level.

#     LIQ_GRAV: Gravity of liquid produced from the property.
#     •   In Texas this is the gravity of the discovery well in the field. 
#     •   When available in Texas, the gravity is determined from the latest filed reports with the State Comptroller. 

#     ALLOC_PLUS: This column identifies whether an Entity ID is part of the TX Allocated dataset. Possible values are:
#     •   Y – Indicated that an Entity ID is an part of the TX Allocated dataset
#     •   N – Indicates an Entity ID is unallocated TX oil lease.
#     •   X – All other Entity IDs
#     To properly use the PDEN_DESC table, all queries must reference this column. If a user wants to query using TX Allocated data, then only records with an ALLOC_PLUS value of Y or X should be queried. To query using unallocated data, records with an ALLOC_PLUS value of N or X should be used. Without referencing these columns, data and production in Texas will be double counted. 

# NPH_API_NOS NOTES:
#     Mapping of all API numbers to a unique ENTITY_ID. This table allows you to locate a producing entity based on the API number.  For example, in Texas, production is reported on the lease level, but you can have multiple wells on a lease. With this table you can query the ALL_API_NO field, get back the ENTITY_ID and then query the PDEN_DESC table to locate the producing entity’s header information or go directly to the monthly production volumes in PDEN_PROD.

# ----------------- Information -------------------

table_field_types = list(
    
    `PDEN_DESC` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `CMN`                    = "VARCHAR2(1)",
        `DISTRICT`               = "VARCHAR2(50)",
        `PDEN_TYPE`              = "VARCHAR2(12)",
        `PROD_TYPE`              = "VARCHAR2(50)",
        `STATE`                  = "VARCHAR2(10)",
        `COUNTRY`                = "VARCHAR2(3)",
        `PDEN_NAME`              = "VARCHAR2(100)",
        `API_NO`                 = "VARCHAR2(20)",
        `COMP_DATE`              = "DATE",
        `OFFSHORE`               = "VARCHAR2(100)",
        `FIELD`                  = "VARCHAR2(100)",
        `RESERVOIR`              = "VARCHAR2(100)",
        `LEASE_NO`               = "VARCHAR2(30)",
        `COMMINGLE_NO`           = "VARCHAR2(16)",
        `COMMINGLE_DATE`         = "DATE",
        `COUNTY_ID`              = "VARCHAR2(6)",
        `COUNTY`                 = "VARCHAR2(63)",
        `WELL_NO`                = "VARCHAR2(50)",
        `CURR_OPER_ID`           = "NUMBER(9)",
        `CURR_OPER_NO`           = "VARCHAR2(10)",
        `CURR_OPER_NAME`         = "VARCHAR2(75)",
        `LIQ_GATH_NAME_1`        = "VARCHAR2(75)",
        `GAS_GATH_NAME_1`        = "VARCHAR2(75)",
        `STATUS`                 = "VARCHAR2(50)",
        `DRILL_TYPE`             = "VARCHAR2(1)",
        `ELEVATION`              = "NUMBER(10,5)",
        `ELEVATION_TYPE`         = "VARCHAR2(10)",
        `TOTAL_DEPTH`            = "NUMBER(11,5)",
        `UPPER_PERF`             = "NUMBER(11,5)",
        `LOWER_PERF`             = "NUMBER(11,5)",
        `LIQ_GRAV`               = "NUMBER(15,6)",
        `GAS_GRAV`               = "NUMBER(15,6)",
        `LIQ_DAILY`              = "NUMBER(9)",
        `GAS_DAILY`              = "NUMBER(9)",
        `LIQ_CUM`                = "NUMBER(15,4)",
        `GAS_CUM`                = "NUMBER(14,4)",
        `LATITUDE`               = "NUMBER(12,7)",
        `LONGITUDE`              = "NUMBER(12,7)",
        `LOC_REMARK`             = "VARCHAR2(150)",
        `FIRST_PROD_DATE`        = "DATE",
        `LAST_PROD_DATE`         = "DATE",
        `LATEST_LIQ`             = "NUMBER(9)",
        `LATEST_GAS`             = "NUMBER(14,4)",
        `LATEST_WTR`             = "NUMBER(14)",
        `LATEST_WCNT`            = "NUMBER(4)",
        `PRIOR12_LIQ`            = "NUMBER(9)",
        `PRIOR12_GAS`            = "NUMBER(9)",
        `PRIOR12_WTR`            = "NUMBER(14)",
        `FIRST_LIQ`              = "NUMBER(9)",
        `FIRST_GAS`              = "NUMBER(14,4)",
        `FIRST_WTR`              = "NUMBER(9)",
        `FIRST12_LIQ`            = "NUMBER(9)",
        `FIRST12_GAS`            = "NUMBER(14)",
        `FIRST12_WTR`            = "NUMBER(14)",
        `WTR_CUM`                = "NUMBER(15,4)",
        `WTR_YEAR`               = "NUMBER(14,4)",
        `LIQ_YEAR`               = "NUMBER(14,4)",
        `GAS_YEAR`               = "NUMBER(14,4)",
        `LOCATION`               = "VARCHAR2(75)",
        `SECTION`                = "VARCHAR2(6)",
        `QTR_QTR`                = "VARCHAR2(20)",
        `MERID`                  = "VARCHAR2(50)",
        `OCS_AREA`               = "VARCHAR2(75)",
        `GOR`                    = "NUMBER(15,4)",
        `YIELD`                  = "NUMBER(15,4)",
        `RKB_ELEV`               = "NUMBER(10,5)",
        `WATER_DEPTH`            = "NUMBER(10,5)",
        `RES_VERT_DEPTH`         = "NUMBER(10,5)",
        `MAX_VERT_DEPTH`         = "NUMBER(10,5)",
        `SPUD_DATE`              = "DATE",
        `LATITUDE_BOTM`          = "NUMBER(12,7)",
        `LONGITUDE_BOTM`         = "NUMBER(12,7)",
        `LATITUDE_EX1`           = "NUMBER(12,7)",
        `LONGITUDE_EX1`          = "NUMBER(12,7)",
        `PRIOR_LIQ_CUM`          = "NUMBER(14,4)",
        `PRIOR_GAS_CUM`          = "NUMBER(14,4)",
        `PRIOR_WTR_CUM`          = "NUMBER(14,4)",
        `BASIN`                  = "VARCHAR2(75)",
        `COMMON_OPER_NAME`       = "VARCHAR2(75)",
        `LESSEE_AVAIL`           = "VARCHAR2(1)",
        `PGC_AREA`               = "VARCHAR2(10)",
        `QUAD_NAME`              = "VARCHAR2(30)",
        `ABSTRACT`               = "VARCHAR2(15)",
        `SURVEY`                 = "VARCHAR2(75)",
        `TX_BLOCK`               = "VARCHAR2(15)",
        `TX_SEC`                 = "VARCHAR2(10)",
        `SUBSURVEY`              = "VARCHAR2(50)",
        `TX_SCRAP`               = "VARCHAR2(15)",
        `FIELD_NO`               = "VARCHAR2(30)",
        `MONTHS_PRODUCED`        = "NUMBER(6)",
        `REPORTED_OPER_NAME`     = "VARCHAR2(75)",
        `FORMATION`              = "VARCHAR2(100)",
        `PEAK_GAS`               = "NUMBER(14,4)",
        `PEAK_LIQ`               = "NUMBER(14,4)",
        `LATEST_TEST_DATE`       = "DATE",
        `LATEST_FLOW_RES`        = "NUMBER(14,4)",
        `LATEST_WHSIP`           = "NUMBER(14,4)",
        `TWP`                    = "VARCHAR2(6)",
        `RNG`                    = "VARCHAR2(6)",
        `WELL_ID`                = "NUMBER(38)",
        `LEASE_ID`               = "NUMBER(38)",
        `ALLOC_PLUS`             = "VARCHAR2(1)",
        `FIRST6_LIQ`             = "NUMBER(15,4)",
        `FIRST6_GAS`             = "NUMBER(15,4)",
        `FIRST6_WTR`             = "NUMBER(15,4)",
        `FIRST24_LIQ`            = "NUMBER(15,4)",
        `FIRST24_GAS`            = "NUMBER(15,4)",
        `FIRST24_WTR`            = "NUMBER(15,4)",
        `FIRST60_LIQ`            = "NUMBER(15,4)",
        `FIRST60_GAS`            = "NUMBER(15,4)",
        `FIRST60_WTR`            = "NUMBER(15,4)",
        `FIRST6_BOE`             = "NUMBER(15,4)",
        `FIRST12_BOE`            = "NUMBER(15,4)",
        `FIRST24_BOE`            = "NUMBER(15,4)",
        `FIRST60_BOE`            = "NUMBER(15,4)",
        `FIRST6_MMCFGE`          = "NUMBER(15,4)",
        `FIRST12_MMCFGE`         = "NUMBER(15,4)",
        `FIRST24_MMCFGE`         = "NUMBER(15,4)",
        `FIRST60_MMCFGE`         = "NUMBER(15,4)",
        `DECL_3MO_LIQ`           = "NUMBER(15,4)",
        `DECL_3MO_GAS`           = "NUMBER(15,4)",
        `DECL_3MO_WTR`           = "NUMBER(15,4)",
        `DECL_12MO_LIQ`          = "NUMBER(15,4)",
        `DECL_12MO_GAS`          = "NUMBER(15,4)",
        `DECL_12MO_WTR`          = "NUMBER(15,4)",
        `DECL_24MO_LIQ`          = "NUMBER(15,4)",
        `DECL_24MO_GAS`          = "NUMBER(15,4)",
        `DECL_24MO_WTR`          = "NUMBER(15,4)",
        `DECL_60MO_LIQ`          = "NUMBER(15,4)",
        `DECL_60MO_GAS`          = "NUMBER(15,4)",
        `DECL_60MO_WTR`          = "NUMBER(15,4)",
        `GOR_2ND_MO`             = "NUMBER(22,2)",
        `GOR_LATEST_MO`          = "NUMBER(22,2)",
        `CFGED_PRAC_IP`          = "NUMBER(15,4)",
        `CFGED_CUR_RATE`         = "NUMBER(15,4)",
        `MMCFGE_CUM`             = "NUMBER(15,4)",
        `BCFGE_CUM`              = "NUMBER(15,4)",
        `GOR_CUM`                = "NUMBER(22,2)",
        `MAX_ACTV_WELLS`         = "NUMBER(10)",
        `PEAK_LIQ_DAILY`         = "NUMBER(15,4)",
        `PEAK_GAS_DAILY`         = "NUMBER(15,4)",
        `PEAK_BOE`               = "NUMBER(15,4)",
        `PEAK_MMCFGE`            = "NUMBER(15,4)",
        `YIELD_2ND_MO`           = "NUMBER(15,4)",
        `YIELD_LATEST_MO`        = "NUMBER(15,4)",
        `LIQ_PRAC_IP_DAILY`      = "NUMBER(15,4)",
        `GAS_PRAC_IP_DAILY`      = "NUMBER(15,4)",
        `LIQ_MAX_DAILY`          = "NUMBER(15,4)",
        `GAS_MAX_DAILY`          = "NUMBER(15,4)",
        `WTR_DAILY`              = "NUMBER(15,4)",
        `BOE_CUM`                = "NUMBER(15,4)",
        `MAX_WTR_DAILY`          = "NUMBER(15,4)",
        `BOE_PRAC_IP`            = "NUMBER(15,4)",
        `PEAK_GAS_MONTH`         = "DATE",
        `PEAK_GAS_MONTH_NO`      = "NUMBER(5)",
        `PEAK_LIQ_MONTH`         = "DATE",
        `PEAK_LIQ_MONTH_NO`      = "NUMBER(5)",
        `PEAK_DAILY_GAS_MONTH`   = "DATE",
        `PEAK_DAILY_GAS_MONTH_NO`= "NUMBER(5)",
        `PEAK_DAILY_LIQ_MONTH`   = "DATE",
        `PEAK_DAILY_LIQ_MONTH_NO`= "NUMBER(5)",
        `PEAK_BOE_MONTH`         = "DATE",
        `PEAK_BOE_MONTH_NO`      = "NUMBER(5)",
        `PEAK_MMCFGE_MONTH`      = "DATE",
        `PEAK_MMCFGE_MONTH_NO`   = "NUMBER(5)"
    ),

    `PDEN_PROD` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `PROD_DATE`              = "DATE",
        `LIQ`                    = "NUMBER",
        `GAS`                    = "NUMBER",
        `WTR`                    = "NUMBER",
        `WCNT`                   = "NUMBER",
        `DAYS`                   = "NUMBER"
    ),

    `PDEN_SALE` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `SELLER_NAME`            = "VARCHAR2(75)",
        `BUYER_NAME`             = "VARCHAR2(75)",
        `VOLUME`                 = "NUMBER(14,2)",
        `VALUE`                  = "NUMBER(14,2)",
        `PRICE`                  = "NUMBER(14,2)",
        `SALE_DATE`              = "DATE",
        `PROD_TYPE`              = "VARCHAR2(12)",
        `EXEMPT_VALUE`           = "NUMBER(14,2)",
        `COST`                   = "NUMBER(14,2)",
        `NET_VALUE`              = "NUMBER(14,2)",
        `NET_PRICE`              = "NUMBER(14,2)",
        `LIQ_GRAV`               = "NUMBER(6,2)",
        `NYMX_CM_DIFF`           = "NUMBER(14,4)",
        `NYMX_OM_DIFF`           = "NUMBER(14,4)",
        `MCD`                    = "NUMBER(14,4)",
        `KOCH_WTI_DIFF`          = "NUMBER(14,4)",
        `BUYER_WTI_DIFF`         = "NUMBER(14,4)",
        `BUYER_WTS_DIFF`         = "NUMBER(14,4)",
        `PPLUS_KOCH_DIFF`        = "NUMBER(14,4)",
        `PPLUS_WTI_DIFF`         = "NUMBER(14,4)",
        `PPLUS_WTS_DIFF`         = "NUMBER(14,4)"
    ),

    `PDEN_WELL_TEST` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `SPOT_ID`                = "NUMBER(9)",
        `TEST_DATE`              = "DATE",
        `WELL_NO`                = "VARCHAR2(7)",
        `GAS_CUM`                = "NUMBER(14,4)",
        `POTENTIAL`              = "NUMBER(11,4)",
        `POTENTIAL_CALC`         = "VARCHAR2(1)",
        `GOR`                    = "NUMBER(15,6)",
        `FLOW_PRES`              = "NUMBER(9)",
        `FLOWOZ`                 = "NUMBER(15,6)",
        `WHSIP`                  = "NUMBER(9)",
        `SIPOZ`                  = "NUMBER(15,6)",
        `BHP`                    = "NUMBER(9)",
        `BHP_CALC`               = "VARCHAR2(1)",
        `BHPOZ`                  = "NUMBER(15,6)",
        `GAS_GRAV`               = "NUMBER(14,4)",
        `LIQ_GRAV`               = "NUMBER(14,4)",
        `GAS_TEST_VOL`           = "NUMBER(9)",
        `LIQ_TEST_VOL`           = "NUMBER(14,4)",
        `WAT_TEST_VOL`           = "NUMBER(9)",
        `TEST_TYPE`              = "VARCHAR2(20)",
        `PROD_METHOD`            = "VARCHAR2(20)",
        `CHOKE_SIZE`             = "VARCHAR2(8)",
        `BSW_PERCENT`            = "VARCHAR2(8)",
        `CAS_PRES`               = "NUMBER(8,2)",
        `TBG_PRES`               = "NUMBER(8,2)"
    ),

    `PDEN_INJ` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `INJ_DATE`               = "DATE",
        `WTR_INJ`                = "NUMBER(9)",
        `GAS_INJ`                = "NUMBER(9)",
        `INJ_PSI`                = "NUMBER(9)",
        `CAS_PRES`               = "NUMBER(9)",
        `OTHER_INJ`              = "NUMBER(9)",
        `WCNT`                   = "NUMBER(4)"
    ),

    `NPH_WELLSPOTS` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `SPOT_ID`                = "NUMBER(9)",
        `STATE`                  = "VARCHAR2(10)",
        `ALL_API_NO`             = "VARCHAR2(20)",
        `WELL_NAME`              = "VARCHAR2(50)",
        `WELL_NO`                = "VARCHAR2(50)",
        `LATITUDE`               = "NUMBER(14,8)",
        `LONGITUDE`              = "NUMBER(14,8)",
        `LATITUDE_EX1`           = "NUMBER(14,8)",
        `LONGITUDE_EX1`          = "NUMBER(14,8)",
        `SYMBOL`                 = "NUMBER(9)",
        `RELIABILITY`            = "VARCHAR2(50)",
        `UPPER_PERF`             = "NUMBER(9)",
        `LOWER_PERF`             = "NUMBER(9)",
        `PROD_TYPE`              = "VARCHAR2(50)",
        `STATUS`                 = "VARCHAR2(50)",
        `DRILL_TYPE`             = "VARCHAR2(3)",
        `ELEVATION`              = "NUMBER(14,8)",
        `ELEVATION_TYPE`         = "VARCHAR2(10)",
        `TOTAL_DEPTH`            = "NUMBER(14,8)",
        `PLUG_DATE`              = "DATE",
        `COMP_DATE`              = "DATE",
        `LAST_OPER_NAME`         = "VARCHAR2(75)",
        `ABSTRACT`               = "VARCHAR2(15)",
        `SURVEY`                 = "VARCHAR2(75)",
        `TX_BLOCK`               = "VARCHAR2(15)",
        `TX_SEC`                 = "VARCHAR2(10)",
        `SUBSURVEY`              = "VARCHAR2(50)",
        `TX_SCRAP`               = "VARCHAR2(15)",
        `LOC_REMARK`             = "VARCHAR2(50)"
    ),

    `NPH_API_NOS` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `ALL_API_NO`             = "VARCHAR2(20)"
    ),

    `NPH_OPER_ADDR` = c(
        `ASSOC_ID`               = "NUMBER(9)",
        `ADDR_NO`                = "NUMBER",
        `ADDR_TYPE`              = "VARCHAR2(12)",
        `ADDR_1`                 = "VARCHAR2(75)",
        `ADDR_2`                 = "VARCHAR2(75)",
        `CITY`                   = "VARCHAR2(40)",
        `STATE_ABRV`             = "VARCHAR2(12)",
        `ZIP`                    = "VARCHAR2(12)",
        `COUNTRY`                = "VARCHAR2(12)",
        `PHONE`                  = "VARCHAR2(20)",
        `FAX`                    = "VARCHAR2(20)"
    ),

    `NPH_PDEN_TOPS` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `SEQ_NO`                 = "NUMBER(5)",
        `RES_DEPTH`              = "NUMBER(5)",
        `COMP_RES`               = "VARCHAR2(1)",
        `PROD_RES`               = "VARCHAR2(1)",
        `RESERVOIR`              = "VARCHAR2(100)"
    ),

    `NPH_BOTMHOLES` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `SPOT_ID`                = "NUMBER(9)",
        `BOTM_ID`                = "NUMBER(9)",
        `LATITUDE`               = "NUMBER(14,8)",
        `LONGITUDE`              = "NUMBER(14,8)",
        `LATITUDE_EX1`           = "NUMBER(14,8)",
        `LONGITUDE_EX1`          = "NUMBER(14,8)",
        `SYMBOL`                 = "NUMBER(9)",
        `RELIABILITY`            = "VARCHAR2(50)",
        `DRILL_TYPE`             = "VARCHAR2(3)",
        `ALL_API_NO`             = "VARCHAR2(20)",
        `SURF_LATITUDE`          = "NUMBER(14,8)",
        `SURF_LONGITUDE`         = "NUMBER(14,8)",
        `SURF_LATITUDE_EX1`      = "NUMBER(14,8)",
        `SURF_LONGITUDE_EX1`     = "NUMBER(14,8)"
    ), 

    `PERMITS` = c(
        `ENTITY_ID`              = "NUMBER(9)",
        `CMN`                    = "NUMBER",
        `PURPOSE`                = "VARCHAR2(12)",
        `API_NO`                 = "VARCHAR2(20)",
        `PERMIT_NO`              = "VARCHAR2(30)",
        `CASE_NO`                = "VARCHAR2(10)",
        `OPER_NAME`              = "VARCHAR2(75)",
        `OPER_ADDR_1`            = "VARCHAR2(75)",
        `OPER_ADDR_2`            = "VARCHAR2(75)",
        `OPER_CITY`              = "VARCHAR2(40)",
        `OPER_STATE`             = "VARCHAR2(12)",
        `OPER_ZIP`               = "VARCHAR2(12)",
        `OPER_NO`                = "VARCHAR2(9)",
        `DISTRICT`               = "VARCHAR2(16)",
        `COUNTY`                 = "VARCHAR2(50)",
        `LEASE_NAME`             = "VARCHAR2(50)",
        `LEASE_NO`               = "VARCHAR2(12)",
        `WELL_NO`                = "VARCHAR2(32)",
        `TOTAL_DEPTH`            = "VARCHAR2(20)",
        `BLOCK`                  = "VARCHAR2(20)",
        `SURVEY`                 = "VARCHAR2(100)",
        `ABSTRACT_NO`            = "VARCHAR2(15)",
        `MILES`                  = "VARCHAR2(20)",
        `DIRECTION`              = "VARCHAR2(30)",
        `NEAREST_TOWN`           = "VARCHAR2(50)",
        `LEASE_DIST`             = "VARCHAR2(20)",
        `CONTIG_ACRES`           = "VARCHAR2(20)",
        `PERPEN_LEASE_UNIT`      = "VARCHAR2(50)",
        `PERPEN_SUR_SEC`         = "VARCHAR2(50)",
        `BOT_HOLE_LEASE_UNIT`    = "VARCHAR2(50)",
        `BOT_HOLE_SUR_SEC`       = "VARCHAR2(50)",
        `P12`                    = "VARCHAR2(1)",
        `W1A`                    = "VARCHAR2(1)",
        `H2S_AREA`               = "VARCHAR2(1)",
        `H9`                     = "VARCHAR2(1)",
        `MINERAL_RIGHTS`         = "VARCHAR2(1)",
        `REMARKS`                = "VARCHAR2(1)",
        `FILER_NAME`             = "VARCHAR2(50)",
        `FILER_TITLE`            = "VARCHAR2(50)",
        `DATE_FILED`             = "DATE",
        `PHONE`                  = "VARCHAR2(20)",
        `RRC_STAMPED_DATE`       = "DATE",
        `ROW_CHANGED_BY`         = "VARCHAR2(20)",
        `ROW_CHANGED_DATE`       = "DATE",
        `GRANTED_DATE`           = "DATE",
        `POST_DATE`              = "DATE",
        `ASSOC_ID`               = "NUMBER(9)",
        `ADDR_NO`                = "NUMBER(9)",
        `DATE_ENTERED`           = "DATE",
        `SPUD_DATE`              = "DATE",
        `LONGITUDE`              = "NUMBER(12,7)",
        `LATITUDE`               = "NUMBER(12,7)",
        `STATE`                  = "VARCHAR2(12)",
        `PDEN_TYPE`              = "VARCHAR2(20)",
        `DRILL_TYPE`             = "VARCHAR2(10)",
        `PERMIT_TYPE`            = "VARCHAR2(12)",
        `LOCATION`               = "VARCHAR2(31)",
        `SECTION`                = "VARCHAR2(20)",
        `QTRQTR`                 = "VARCHAR2(20)",
        `FTGCOR`                 = "VARCHAR2(10)",
        `FTG1`                   = "VARCHAR2(10)",
        `FTG1DIR`                = "VARCHAR2(10)",
        `FTG2`                   = "VARCHAR2(10)",
        `FTG2DIR`                = "VARCHAR2(10)",
        `COUNTY_ID`              = "VARCHAR2(5)",
        `FIELD_NAME`             = "VARCHAR2(100)",
        `RES_NAME`               = "VARCHAR2(100)",
        `COMP_DATE`              = "DATE",
        `BASIN`                  = "VARCHAR2(75)",
        `DRILLER`                = "VARCHAR2(40)",
        `DRILLER_PHONE`          = "VARCHAR2(15)",
        `RIG_NUM`                = "VARCHAR2(20)",
        `STATUS_DATE`            = "DATE",
        `STATUS`                 = "VARCHAR2(10)",
        `WELL_DEPTH`             = "NUMBER(6)",
        `MEAS_DEPTH`             = "NUMBER(6)",
        `RIG_PRESENT`            = "VARCHAR2(1)",
        `MAST_ID`                = "NUMBER(9)",
        `WELL_ID`                = "NUMBER(9)",
        `RIG_UPDATE_DATE`        = "DATE",
        `DATE_PROD`              = "DATE",
        `NEW_WELL`               = "VARCHAR2(1)",
        `ORPH_WELL`              = "VARCHAR2(1)",
        `LEGAL_SL`               = "VARCHAR2(60)",
        `TWN_SL`                 = "VARCHAR2(3)",
        `TWNDIR_SL`              = "VARCHAR2(1)",
        `RNG_SL`                 = "VARCHAR2(3)",
        `RNGDIR_SL`              = "VARCHAR2(1)",
        `FTG1REF_SL`             = "VARCHAR2(10)",
        `FTG2REF_SL`             = "VARCHAR2(10)",
        `QTRSEC_SL`              = "VARCHAR2(12)",
        `CRTRQD1_SL`             = "VARCHAR2(2)",
        `CRTRQD2_SL`             = "VARCHAR2(2)",
        `BLKNUM_SL`              = "VARCHAR2(4)",
        `SRVYNUM_SL`             = "VARCHAR2(4)",
        `COUNTY_BH`              = "VARCHAR2(15)",
        `LEGAL_BH`               = "VARCHAR2(60)",
        `SEC_BH`                 = "VARCHAR2(4)",
        `TWN_BH`                 = "VARCHAR2(3)",
        `TWNDIR_BH`              = "VARCHAR2(1)",
        `RNG_BH`                 = "VARCHAR2(3)",
        `RNGDIR_BH`              = "VARCHAR2(1)",
        `FTG1_BH`                = "VARCHAR2(6)",
        `FTG1DIR_BH`             = "VARCHAR2(6)",
        `FTG1REF_BH`             = "VARCHAR2(10)",
        `FTG2_BH`                = "VARCHAR2(6)",
        `FTG2DIR_BH`             = "VARCHAR2(6)",
        `FTG2REF_BH`             = "VARCHAR2(10)",
        `QTRSEC_BH`              = "VARCHAR2(12)",
        `FTGCOR_BH`              = "VARCHAR2(3)",
        `CRTRQD1_BH`             = "VARCHAR2(2)",
        `CRTRQD2_BH`             = "VARCHAR2(2)",
        `ABSTNO_BH`              = "VARCHAR2(5)",
        `BLKNAM_BH`              = "VARCHAR2(32)",
        `BLKNUM_BH`              = "VARCHAR2(4)",
        `SRVYNAM_BH`             = "VARCHAR2(32)",
        `SRVYNUM_BH`             = "VARCHAR2(4)",
        `FIELD_1`                = "VARCHAR2(20)",
        `FORM_1`                 = "VARCHAR2(100)",
        `FORM_DEPTH_1`           = "NUMBER(5)",
        `FIELD_2`                = "VARCHAR2(20)",
        `FORM_2`                 = "VARCHAR2(100)",
        `FORM_DEPTH_2`           = "NUMBER(5)",
        `FIELD_3`                = "VARCHAR2(20)",
        `FORM_`                  = "VARCHAR2(100)",
        `FORM_DEPTH_3`           = "NUMBER(5)",
        `FIELD_4`                = "VARCHAR2(20)",
        `FORM_4`                 = "VARCHAR2(100)",
        `FORM_DEPTH_4`           = "NUMBER(5)",
        `FIELD_5`                = "VARCHAR2(20)",
        `FORM_5`                 = "VARCHAR2(100)",
        `FORM_DEPTH_5`           = "NUMBER(5)",
        `FIELD_6`                = "VARCHAR2(20)",
        `FORM_6`                 = "VARCHAR2(100)",
        `FORM_DEPTH_6`           = "NUMBER(5)",
        `FIELD_7`                = "VARCHAR2(20)",
        `FORM_7`                 = "VARCHAR2(100)",
        `FORM_DEPTH_7`           = "NUMBER(5)",
        `FIELD_8`                = "VARCHAR2(20)",
        `FORM_8`                 = "VARCHAR2(100)",
        `FORM_DEPTH_8`           = "NUMBER(5)",
        `WELL_PURP`              = "VARCHAR2(3)",
        `JOB_NUM`                = "VARCHAR2(7)",
        `WORK_TYPE`              = "VARCHAR2(20)",
        `DATE_RELS`              = "DATE",
        `WELL_PROX`              = "VARCHAR2(30)",
        `DRIL_CONT`              = "VARCHAR2(34)",
        `DRIL_ADDR`              = "VARCHAR2(39)",
        `DRIL_CITY`              = "VARCHAR2(25)",
        `DRIL_STATE`             = "VARCHAR2(2)",
        `DRIL_ZIP`               = "VARCHAR2(10)",
        `DRIL_TERM`              = "VARCHAR2(2)",
        `ADD_INFO`               = "VARCHAR2(50)",
        `RECRD_STAT`             = "VARCHAR2(4)",
        `WELL_ACTV`              = "VARCHAR2(3)",
        `MAP_REF`                = "NUMBER",
        `OPER_CONT`              = "VARCHAR2(34)",
        `APPROVED`               = "VARCHAR2(1)",
        `COMP_EXISTS`            = "VARCHAR2(1)",
        `LONGITUDE_EX1`          = "NUMBER(12,7)",
        `LATITUDE_EX1`           = "NUMBER(12,7)",
        `IMAGE_PATH`             = "VARCHAR2(4000)"
    )
)

table_field_labels = list(

`PDEN_DESC` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `CMN`                    = "Internal use.  Ignore this field",
        `DISTRICT`               = "The district within a given state the property is assigned",
        `PDEN_TYPE`              = "Property Type (LEASE/UNIT/WELL/Completion/OTHER/UNKNOWN, etc...)",
        `PROD_TYPE`              = "(aka Well/Lease Type)",
        `STATE`                  = "The state the property is in",
        `COUNTRY`                = "The country the property is located in",
        `PDEN_NAME`              = "(aka Lease/Well Name) Operator assigned lease/well name of the property",
        `API_NO`                 = "API assigned number of a well on the property",
        `COMP_DATE`              = "(aka Completion Date) Latest Completion Date of the property",
        `OFFSHORE`               = "Indicates if the property is in offshore waters",
        `FIELD`                  = "Field name the property is reporting from",
        `RESERVOIR`              = "Reservoir/Formation/Zone/Pool that the property is reported as producing from",
        `LEASE_NO`               = "State number assigned to the property or lease or unit the property is part of",
        `COMMINGLE_NO`           = "(aka Commingle) The commingle number assigned to the property by the state",
        `COMMINGLE_DATE`         = "The date the property was commingled",
        `COUNTY_ID`              = "API State and County codes for the property",
        `COUNTY`                 = "County the property is in",
        `WELL_NO`                = "Operator assigned well number of the property",
        `CURR_OPER_ID`           = "HPDI assigned operator ID number",
        `CURR_OPER_NO`           = "State assigned number of the operator of the property",
        `CURR_OPER_NAME`         = "Current reported operator of a property",
        `LIQ_GATH_NAME_1`        = "The current primary liquid gather for a property",
        `GAS_GATH_NAME_1`        = "The current primary gas gather for a property",
        `STATUS`                 = "The current status of the well such as Active, Inactive, TA, Shut In, etc..",
        `DRILL_TYPE`             = "Indicates whether a property was drilled Horizontally, Vertically, Directionally, or Unknown Orientation",
        `ELEVATION`              = "Elevation of the property",
        `ELEVATION_TYPE`         = "Identifies where elevation was measured from (Ground, RKB, MSL, etc...)",
        `TOTAL_DEPTH`            = "(aka Depth) Total depth the property was drilled to",
        `UPPER_PERF`             = "Upper perforation of the producing property",
        `LOWER_PERF`             = "Lower perforation of the producing property",
        `LIQ_GRAV`               = "Gravity of liquid produced from the property",
        `GAS_GRAV`               = "Gravity of gas produced from the property",
        `LIQ_DAILY`              = "The average daily liquid production over the past 12 months",
        `GAS_DAILY`              = "The average daily gas production over the past 12 months",
        `LIQ_CUM`                = "(aka Liq Sum) Cumulative liquid production for this property that HPDI has on record",
        `GAS_CUM`                = "(aka Gas Sum) Cumulative gas production for this property that HPDI has on record",
        `LATITUDE`               = "Latitude the property is located in (On multi-well properties a well is picked to designate the location of the property)",
        `LONGITUDE`              = "Longitude the property is located in (On multi-well properties a well is picked to designate the location of the property)",
        `LOC_REMARK`             = "Free form description of property location (typically description of Survey/Abstract, or footage calls to go with LOCATION field)",
        `FIRST_PROD_DATE`        = "First date HPDI has reported production for the property (Even though date may be represented as mm/dd/yyyy, it is for the month listed, not just the individual day)",
        `LAST_PROD_DATE`         = "Last date HPDI has reported production for the property (Even though date may be represented as mm/dd/yyyy, it is for the month listed, not just the individual day)",
        `LATEST_LIQ`             = "Liquid production in Bbls on LAST_PROD_DATE",
        `LATEST_GAS`             = "Gas production in MCF on LAST_PROD_DATE",
        `LATEST_WTR`             = "Water production in Bbls on LAST_PROD_DATE",
        `LATEST_WNCT`            = "Number of reported producing wells completions active during LAST_PROD_DATE. In cases where a number is not permitted, 1 is substituted if there was any production. In Kansas, one is always used even though the exact number of wells on the lease is not always used. In almost all other cases, either only one well completion is reported per production number, or a well count is given for the property. In Louisiana where the production is allocated to the well completion level, 1 is always used even though more than one well may have been producing on the original lease",
        `PRIOR12_LIQ`            = "Oil (or Condensate) production reported in Bbls in the twelve months prior to the months included in LIQ_YEAR",
        `PRIOR12_GAS`            = "Gas production reported in MCF in the twelve months prior to the months included in GAS_YEAR",
        `PRIOR12_WTR`            = "Water production reported in Bbls in the twelve months prior to the months included in WTR_YEAR",
        `FIRST_LIQ`              = "Oil (or Condensate) production reported in Bbls during FIRST_PROD_DATE",
        `FIRST_GAS`              = "Gas production reported in MCF during FIRST_PROD_DATE",
        `FIRST_WTR`              = "Water production reported in Bbls during FIRST_PROD_DATE",
        `FIRST12_LIQ`            = "Oil (or Condensate) production reported in Bbls in the year beginning with FIRST_PROD_DATE",
        `FIRST12_GAS`            = "Gas production reported in MCF in the year beginning with FIRST_PROD_DATE",
        `FIRST12_WTR`            = "Water production reported in Bbls in the year beginning with FIRST_PROD_DATE",
        `WTR_CUM`                = "(aka Wtr Sum) Cumulative water production for this property that HPDI has on record",
        `WTR_YEAR`               = "Water production reported in Bbls in the twelve months ending with LAST_PROD_DATE",
        `LIQ_YEAR`               = "Oil (or Condensate) production reported in Bbls in the twelve months ending with LAST_PROD_DATE",
        `GAS_YEAR`               = "Gas production reported in MCF in the twelve months leading ending with LAST_PROD_DATE",
        `LOCATION`               = "Township Range (or MMS Block) of Property",
        `SECTION`                = "Section property is located in",
        `QTR_QTR`                = "Quarter-Quarter the property is located in",
        `MERID`                  = "Meridian legal description is referenced from",
        `OCS_AREA`               = "MMS Offshore area that well is in",
        `GOR`                    = "Gas/Oil Ratio of property",
        `YEILD`                  = "Oil to gas ratio",
        `RKB_ELEV`               = "The RKB Elevation for Federal Offshore properties ** Obsolete Soon",
        `WATER_DEPTH`            = "Depth of water above well in offshore waters",
        `RES_VERT_DEPTH`         = "Vertical Depth of reservoir in Federal Offshore properties ** Obsolete Soon",
        `MAX_VERT_DEPTH`         = "Maximum vertical Depth of well in offshore waters ** Obsolete Soon",
        `SPUD_DATE`              = "Latest date drilling commenced on property",
        `LATITUDE_BOTM`          = "Bottom hole latitude of property",
        `LONGITUDE_BOTM`         = "Bottom hole longitude of property",
        `LATITUDE_EX1`           = "Location of the well in NAD 83",
        `LONGITUDE_EX1`          = "Location of the well in NAD 83",
        `PRIOR_LIQ_CUM`          = "LIQ_CUM Prior to production commencing on FIRST_PROD_DATE ** Not currently in use",
        `PRIOR_GAS_CUM`          = "GAS_CUM Prior to production commencing on FIRST_PROD_DATE ** Not currently in use",
        `PRIOR_WTR_CUM`          = "WTR_CUM Prior to production commencing on FIRST_PROD_DATE ** Not currently in use",
        `BASIN`                  = "The basin a property is located in. Currently these basins are defined by a county cross-reference. HPDI is in the process of defining the basin lines more accurately along geologic boundaries",
        `COMMON_OPER_NAME`       = "Operator name that has been modified to be consistent across states ** Not currently in use",
        `LESSEE_AVAIL`           = "Indicates if any lessee information is available for a given property",
        `PGC_AREA`               = "Potential Gas Committee assigned province that the production is located in",
        `QUAD_NAME`              = "Name of the USGS Quad",
        `FIELD_NO`               = "State assigned field identifier number",
        `ABSTRACT`               = "Abstract number (TX Only)",
        `SURVEY`                 = "Survey name (TX Only)",
        `TX_BLOCK`               = "Block (TX Only)",
        `TX_SEC`                 = "Section (TX Only)",
        `SUBSURVEY`              = "Subsurvey Name (TX Only)",
        `TX_SCRAP`               = "Scrap Number (TX Only)",
        `MONTHS_PRODUCED`        = "Number of months a property has reported production of liquid, gas or water",
        `REPORTED_OPER_NAME`     = "Name of operator as reported to the state",
        `FORMATION`              = "Formation that the property is reported as producing from",
        `PEAK_GAS`               = "Peak gas volume from a properties production history",
        `PEAK_LIQ`               = "peak liquid volume from a properties production history",
        `LATEST_TEST_DATE`       = "Date the latest well test was reported",
        `LATEST_FLOW_RES`        = "Latest well head shut-in pressure reported",
        `LATEST_WHSIP`           = "Latest well head shut-in pressure reported",
        `TWP`                    = "the township the property is located in",
        `RNG`                    = "the range the property is located in",
        `WELL_ID`                = "Internal use unique identifier",
        `LEASE_ID`               = "internal use unique identifier",
        `ALLOC_PLUS`             = "This column identifies whether an Entity ID is part of the TX Allocated dataset. Possible values are:",
        `FIRST6_LIQ`             = "The sum of months 1-6 of oil production, not the first 6 production records. The first month is the first month of the production of any type of product",
        `FIRST6_GAS`             = "The sum of months 1-6 of gas production, not the first 6 production records. The first month is the first month of the production of any type of product",
        `FIRST6_WTR`             = "The sum of months 1-6 of water production, not the first 6 production records. The first month is the first month of the production of any type of product",
        `FIRST24_LIQ`            = "The sum of months 1-24 of oil production, not the first 24 production records. The first month is the first month of the production of any type of product",
        `FIRST24_GAS`            = "The sum of months 1-24 of gas production, not the first 24 production records. The first month is the first month of the production of any type of product",
        `FIRST24_WTR`            = "The sum of months 1-24 of water production, not the first 24 production records. The first month is the first month of the production of any type of product",
        `FIRST60_LIQ`            = "The sum of months 1-60 of oil production, not the first 60 production records. The first month is the first month of the production of any type of product",
        `FIRST60_GAS`            = "The sum of months 1-60 of gas production, not the first 60 production records. The first month is the first month of the production of any type of product",
        `FIRST60_WTR`            = "The sum of months 1-60 of water production, not the first 60 production records. The first month is the first month of the production of any type of product",
        `FIRST6_BOE`             = "The sum for the first 6 months of barrels of oil equivalent (BOE), not the first 6 production records. BOE is defined as = oil + (gas / 6) for any given month",
        `FIRST12_BOE`            = "The sum for the first 12 months of barrels of oil equivalent (BOE), not the first 12 production records. BOE is defined as = oil + (gas / 6) for any given month",
        `FIRST24_BOE`            = "The sum for the first 24 months of barrels of oil equivalent (BOE), not the first 24 production records. BOE is defined as = oil + (gas / 6) for any given month",
        `FIRST60_BOE`            = "The sum for the first 60 months of barrels of oil equivalent (BOE), not the first 60 production records. BOE is defined as = oil + (gas / 6) for any given month",
        `FIRST6_MMCFGE`          = "The sum for the first 6 months of million cubic feet of gas equivalent (MMFCGE), not the first 6 production records. MMCFGE is defined as = ((oil * 6) + (gas) / 1000) for any given month",
        `FIRST12_MMCFGE`         = "The sum for the first 12 months of million cubic feet of gas equivalent (MMFCGE), not the first 12 production records. MMCFGE is defined as = ((oil * 6) + (gas) / 1000) for any given month",
        `FIRST24_MMCFGE`         = "The sum for the first 24 months of million cubic feet of gas equivalent (MMFCGE), not the first 12 production records. MMCFGE is defined as = ((oil * 6) + (gas) / 1000) for any given month",
        `FIRST60_MMCFGE`         = "The sum for the first 60 months of million cubic feet of gas equivalent (MMFCGE), not the first 60 production records. MMCFGE is defined as = ((oil * 6) + (gas) / 1000) for any given month",
        `DECL_3MO_LIQ`           = "The percent decline from the peak month of oil production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_3MO_GAS`           = "The percent decline from the peak month of gas production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_3MO_WTR`           = "The percent decline from the peak month of water production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_12MO_LIQ`          = "The percent decline from the peak month of oil production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_12MO_GAS`          = "The percent decline from the peak month of gas production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_12MO_WTR`          = "The percent decline from the peak month of water production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_24MO_LIQ`          = "The percent decline from the peak month of oil production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_24MO_GAS`          = "The percent decline from the peak month of gas production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_24MO_WTR`          = "The percent decline from the peak month of water production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_60MO_LIQ`          = "The percent decline from the peak month of oil production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_60MO_GAS`          = "The percent decline from the peak month of gas production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `DECL_60MO_WTR`          = "The percent decline from the peak month of water production to the Nth month as a percent of the peak month. Ex: if the decline is for the 3rd month and May was the peak month, August would be the 3rd month used. The formula is: PercentDecline = 100 * ((ProductionMax - ProductionNthMonth) / ProductionMax). If production is 0 in the Nth month, or if we do not have production records for that month yet, the decline percentage is 100%",
        `GOR_2ND_MO`             = "The gas to oil ratio (GOR) for the second month of production. = (gas/oil) * 1000",
        `GOR_LATEST_MO`          = "The gas to oil ratio (GOR) for the latest month of production. = (gas/oil) * 1000",
        `CFGED_PRAC_IP`          = "Cubic feet of gas equivalent per day, practical initial production (PRAC IP). (Prac IP is the based on the second month of production to represent the first 'full' month producing). Cubic feet of gas equivalent per day of the second month of production = (gas + (oil * 6)) * 1000",
        `CFGED_CUR_RATE`         = "Cubic feet of gas equivalent per day of the latest month of production. = (gas + (oil * 6)) * 1000",
        `MMCFGE_CUM`             = "The sum of the millions of cubic feet of gas per day equivalent. One month's worth is = (gas + (oil * 6) ) /1000",
        `BCFGE_CUM`              = "The sum of the billions of cubic feet of gas per day equivalent. One month's worth is = (gas + (oil * 6) ) /1000 / 1000 (or actually = CUM_MMCFGE/1000)",
        `GOR_CUM`                = "Cumulative gas to oil ratio (GOR) = sum(gas) / sum * 1000",
        `MAX_ACTV_WELLS`         = "The max number of wells ever on the producing entity. A producing entity may be a well, a lease, a field, a block, etc",
        `PEAK_LIQ_DAILY`         = "Peak oil per day. If the number of 'Days On' is available then it is used to calculate the amount per day, otherwise the number of days in the month is used",
        `PEAK_GAS_DAILY`         = "Peak gas per day. If the number of 'Days On' is available then it is used to calculate the amount per day, otherwise the number of days in the month is used",
        `PEAK_BOE`               = "Peak barrel of oil equivalent (BOE). BOE = oil + (gas / 6)",
        `PEAK_MMCFGE`            = "Peak million cubic feet of gas equivalent (MMCFGE). MMCFGE = ((oil * 6) + gas) / 1000",
        `YIELD_2ND_MO`           = "2nd month's oil to gas ratio (Yield). = (oil / gas) * 1000. 2nd month is the first month after the first month of production, not the second production record",
        `YIELD_LATEST_MO`        = "Latest month's oil to gas ratio (Yield). = (oil / gas) * 1000",
        `LIQ_PRAC_IP_DAILY`      = "Oil practical initial production (PRAC IP) per day. (Prac IP is the based on the second month of production to represent the first 'full' month producing) . So if Jan was the first production record and the second was Sept, Sept would be considered the second month for Prac IP calculations",
        `GAS_PRAC_IP_DAILY`      = "Gas practical initial production (PRAC IP) per day. (Prac IP is the based on the second month of production to represent the first 'full' month producing). So if Jan was the first production record and the second was Sept, Sept would be considered the second month for Prac IP calculations",
        `LIQ_MAX_DAILY`          = "This column was a duplicate of PEAK_LIQ_DAILY and thus removed from the application with a version number >= 6.0.1.2. The column still exists in the database but is populated with all zeros",
        `GAS_MAX_DAILY`          = "This column was a duplicate of PEAK_GAS_DAILY and thus removed from the application with a version number >= 6.0.1.2. The column still exists in the database but is populated with all zeros",
        `WTR_DAILY`              = "Average water per day. If 'Days On' is available it is used for the calculations, otherwise the number of days in the month is used",
        `BOE_CUM`                = "Cumulative barrels of oil equivalent (BOE). One month's BOE = oil + (gas / 6)",
        `MAX_WTR_DAILY`          = "Max water per day. If 'Days On' is available it is used for the calculations, otherwise the number of days in the month is used",
        `BOE_PRAC_IP`            = "Barrel of oil equivalent (BOE) practical initial production (PRAC IP). (Prac IP is the based on the second month of production to represent the first 'full' month producing). BOE = oil + (gas/6). If 'Days On' is available it is used for the calculations, otherwise the number of days in the month is used. So if Jan was the first production record and the second was Sept, Sept would be considered the second month for Prac IP calculations",
        `PEAK_GAS_MONTH`         = "Month in which the peak gas production occurred",
        `PEAK_GAS_MONTH_NO`      = "The month number of the peak volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing gas, not just any product",
        `PEAK_LIQ_MONTH`         = "Month in which the peak oil production occurred",
        `PEAK_LIQ_MONTH_NO`      = "The month number of the peak volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing oil not just any product",
        `PEAK_DAILY_GAS_MONTH`   = "Month in which the peak daily gas production occurred. If 'Days On' is available it is used for the calculations, otherwise the number of days in the month is used",
        `PEAK_DAILY_GAS_MONTH_NO`= " The month number of the peak daily volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing gas, not just any product",
        `PEAK_DAILY_LIQ_MONTH`   = "Month in which the peak daily oil production occurred. If 'Days On' is available it is used for the calculations, otherwise the number of days in the month is used",
        `PEAK_DAILY_LIQ_MONTH_NO`= "The month number of the peak daily volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing oil not just any product",
        `PEAK_BOE_MONTH`         = "Month in which the peak barrels of oil equivalent (BOE) production occurred. BOE= oil + (gas / 6 )",
        `PEAK_BOE_MONTH_NO`      = "The month number of the peak BOE volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing oil or gas",
        `PEAK_MMCFGE_MONTH`      = "Month in which the peak MMCFGE production occurred. MMCFGE = (gas + oil * 6) ) /1000",
        `PEAK_MMCFGE_MONTH_NO`   = "The month number of the peak MMCFGE volume. If it occurred in the first month of production then it is 1, in the second it is 2 and so on. It should be noted that the first month for this calculation is the month that it first began producing oil or gas"
),

`PDEN_PROD` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `PROD_DATE`              = "Date during which production occurred",
        `LIQ`                    = "Oil reported during production interval in BBLS",
        `GAS`                    = "Gas reported during production interval in MCF",
        `WTR`                    = "Water reported during production interval in BBLS",
        `WCNT`                   = "Number of reported producing wells completions active during the interval. In cases where a number is not permitted, one is substituted if there was any production. In Kansas, one is always used even though the exact number of wells on the lease is not always used. In almost all other cases, either only one well completion is reported per production number, or a well count is given for the property. In Louisiana where the production is allocated to the well completion level, one is always used even though more than one well may have been producing on the original lease",
        `DAYS`                   = "Number of reported days the well has produced in a month. Only for AZ,CA,CO, FO GULF, MT, ND, NM"
),

`PDEN_SALE` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `SELLER_NAME`            = "Name of seller selling the product (Typically, but not always the operator)",
        `BUYER_NAME`             = "Purchaser of the product (Typically, but not always the gatherer)",
        `VOLUME`                 = "Total volume sold",
        `VALUE`                  = "Total price paid for the product",
        `PRICE`                  = "Price per unit (Value/Volume) paid for the product",
        `SALE_DATE`              = "Date the sale took place",
        `PROD_TYPE`              = "Type of product in the transaction",
        `EXEMPT_VALUE`           = "Value that is exempt from taxes",
        `COST`                   = "The actual marketing cost incurred",
        `NET_VALUE`              = "Total value - Cost",
        `NET_PRICE`              = "Net Value/Volume",
        `LIQ_GRAV`               = "Liquid gravity of product sold",
        `NYMX_CM_DIFF`           = "Differential of price to NYMX Contract Month Pricing",
        `NYMX_OM_DIFF`           = "Differential of price to NYMX Operating Month Pricing",
        `MCD`                    = "Midland-Cushing Differential",
        `KOCH_WTI_DIFF`          = "Price differential to Koch posted WTI",
        `BUYER_WTI_DIFF`         = "Price differential to buyer’s posted WTI price",
        `BUYER_WTS_DIFF`         = "Price differential to buyer’s posted WTS price",
        `PPLUS_KOCH_DIFF`        = "No longer used",
        `PPLUS_WTI_DIFF`         = "No longer used",
        `PPLUS_WTS_DIFF`         = "No longer used"
),

`PDEN_WELL_TEST` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `SPOT_ID`                = "DI Desktop assigned ID unique to the surface well spot",
        `TEST_DATE`              = "Date the well test was performed",
        `WELL_NO`                = "(aka Well) Well number if more than one well is on the property listed above on the detail page",
        `GAS_CUM`                = "Cumulative reported gas at the time of the well test",
        `POTENTIAL`              = "Potential reported for well",
        `POTENTIAL_CALC`         = "Potential calculated or measured",
        `GOR`                    = "Gas oil ratio",
        `FLOW_PRES`              = "Well head flowing pressure",
        `FLOWOZ`                 = "Flowing pressure divided by Z-Factor",
        `WHSIP`                  = "Well head shut-in pressure",
        `SIPOZ`                  = "(aka P/Z) Calculated BHP/Z if WHSIP provided",
        `BHP`                    = "BHP if available",
        `BHP_CALC`               = "Indicates if calculated BHP",
        `BHPOZ`                  = "BHP/Z Factor if available",
        `GAS_GRAV`               = "Gas Gravity reported during test",
        `LIQ_GRAV`               = "Liq Gravity reported during test",
        `GAS_TEST_VOL`           = "Daily gas production reported during the test",
        `LIQ_TEST_VOL`           = "Daily liquid production reported during the test",
        `WAT_TEST_VOL`           = "Daily water production reported during the test",
        `TEST_TYPE`              = "Type of test",
        `PROD_METHOD`            = "Production method indicating during test",
        `CHOKE_SIZE`             = "Choke used during test",
        `BSW_PERCENT`            = "Impurities and water contained in the fluid produced by an oil well",
        `CAS_PRES`               = "The pressure built up between the casing and the tubing",
        `TBG_PRES`               = "Tubing Pressure"
),

`PDEN_INJ` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `INJ_DATE`               = "Date injection occurred",
        `WTR_INJ`                = "Water Volume Injected",
        `GAS_INJ`                = "Gas Volume Injected",
        `INJ_PSI`                = "Injection Pressure",
        `CAS_PRES`               = "The pressure built up between the casing and the tubing",
        `OTHER_INJ`              = "Volume of product injected if product is unreported or not water or Gas",
        `WCNT`                   = "Number of reported injection wells during period. Set to 1 if not reported otherwise."
),

`NPH_WELLSPOTS` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to the producing property the well is for",
        `SPOT_ID`                = "HPDI assigned ID unique to this well spot (may be zero if spot has no information besides a lat/long)",
        `STATE`                  = "The state the property is in",
        `ALL_API_NO`             = "(aka API No) API number of the well",
        `WELL_NAME`              = "Well name",
        `WELL_NO`                = "Well number",
        `LATITUDE`               = "Surface Latitude of well, NAD 27",
        `LONGITUDE`              = "Surface Longitude of well, NAD 27",
        `LATITUDE_EX1`           = "Surface Latitude of well, NAD 83",
        `LONGITUDE_EX1`          = "Surface Longitude of well, NAD 83",
        `SYMBOL`                 = "HPDI ID for determining symbol of well spot to draw on map",
        `RELIABILITY`            = "Code used to determine source of well spot info",
        `UPPER_PERF`             = "Upper perf of well",
        `LOWER_PERF`             = "Lower perf of well",
        `PROD_TYPE`              = "(aka Product) Primary well product",
        `STATUS`                 = "Reported well status",
        `DRILL_TYPE`             = "Indicates whether a property was drilled Horizontally, Vertically, Directionally, or Unknown Orientation",
        `ELEVATION`              = "Elevation of the property",
        `ELEVATION_TYPE`         = "Identifies where elevation was measured from (Ground, RKB, MSL, etc...)",
        `TOTAL_DEPTH`            = "(aka Depth) Total depth the property was drilled to",
        `PLUG_DATE`              = "Date well was plugged",
        `COMP_DATE`              = "Latest completion Date of the well",
        `LAST_OPER_NAME`         = "Operator Name",
        `ABSTRACT`               = "Abstract number (TX Only)",
        `SURVEY`                 = "Survey name (TX Only)",
        `TX_BLOCK`               = "Block (TX Only)",
        `TX_SEC`                 = "Section (TX Only)",
        `SUBSURVEY`              = "Subsurvey Name (TX Only)",
        `TX_SCRAP`               = "Scrap Number (TX Only)",
        `LOC_REMARK`             = "Free form description of property location (typically description of Survey/Abstract, or footage calls to go with LOCATION field)."
),

`NPH_API_NOS` = c(
        `ENTITY_ID`              = "HPDI assigned ID unique to a given property",
        `ALL_API_NO`             = "(aka API No) API number of the well."
),

`NPH_OPER_ADDR` = c(
        `ASSOC_ID`               = "DI Desktop assigned ID unique to a given operator. ASSOC_ID on this table joins to the column CURR_OPER_ID on PDEN_DESC",
        `ADDR_NO`                = "Operator address number",
        `ADDR_TYPE`              = "Operator address type (i.e. mailing, physical)",
        `ADDR_1`                 = "Operator address 1",
        `ADDR_2`                 = "Operator address 2",
        `CITY`                   = "Operator city",
        `STATE_ABRV`             = "Operator state",
        `ZIP`                    = "Operator zip",
        `COUNTRY`                = "Operator country",
        `PHONE`                  = "Operator phone number",
        `FAX`                    = "Operator fax number."
),

`NPH_PDEN_TOPS` = c(
        `ENTITY_ID`              = "DI Desktop assigned ID unique to a given property",
        `SEQ_NO`                 = "Sequence of the pool",
        `RES_DEPTH`              = "Depth of the reservoir",
        `COMP_RES`               = "Completion reservoir",
        `PROD_RES`               = "Production reservoir",
        `RESERVOIR`              = "Reservoir name"
),

`NPH_BOTMHOLES` = c(
        `ENTITY_ID`              = "DI Desktop assigned ID unique to the producing property",
        `SPOT_ID`                = "DI Desktop assigned ID unique to the surface well spot",
        `BOTM_ID`                = "DI Desktop assigned ID unique to the bottom hole spot",
        `LATITUDE`               = "Bottom hole Latitude of well",
        `LONGITUDE`              = "Bottom hole Longitude of well",
        `LATITUDE_EX1`           = "Bottom hole Latitude of well, NAD83",
        `LONGITUDE_EX1`          = "Bottom hole Longitude of well, NAD83",
        `SYMBOL`                 = "DI Desktop ID for determining symbol of well spot to draw on map",
        `RELIABILITY`            = "Code used to determine source of well spot info",
        `DRILL_TYPE`             = "Indicates whether a property was drilled Horizontally, Vertically, Directionally, or Unknown Orientation",
        `ALL_API_NO`             = "(aka API No) API number of the well",
        `SURF_LATITUDE`          = "Surface Latitude of well",
        `SURF_LONGITUDE`         = "Surface Longitude of well",
        `SURF_LATITUDE_EX1`      = "Surface Latitude of well, NAD83",
        `SURF_LONGITUDE_EX1`     = "Surface Longitude of well, NAD83"
),

`PERMITS` = c(
        `ENTITY_ID`              = "Unique ID for finding a permit. Relates to DrillingInfo’s PermitID",
        `CMN`                    = "Constant Value '1'",
        `PURPOSE`                = "Purpose of Well. Identifies whether a well is a Wildcat",
        `API_NO`                 = "Well Api Number",
        `PERMIT_NO`              = "State Permit Number",
        `CASE_NO`                = "Unused",
        `CURR_OPER_NAME`         = "Operator Who Filed Permit",
        `OPER_ADDR_1`            = "Operator Street Address Line 1",
        `OPER_ADDR_2`            = "Operator Street Address Line 2",
        `OPER_CITY`              = "Operator City",
        `OPER_STATE`             = "Operator State",
        `ZIP`                    = "Operator Zip Code",
        `CURR_OPER_NO`           = "Operator State Code",
        `DISTRICT`               = "State District (Such as RRC District)",
        `COUNTY`                 = "Surface Location County",
        `LEASE_NAME`             = "Surface Location Well Name",
        `LEASE_NO`               = "State Lease Number if available",
        `WELL_NO`                = "Surface Location Well Number",
        `TOTAL_DEPTH`            = "Permitted total depth is used when available. Otherwise other depth values are used (i.e. measured depth, TVD, depth on the completion report, etc.)",
        `BLOCK`                  = "Surface Location Block Number (Texas)",
        `SURVEY`                 = "Surface Location Survey Name (Texas)",
        `ABSTRACT_NO`            = "Surface Location Abstract Number (Texas)",
        `MILES`                  = "The number of miles to the nearest town",
        `DIRECTION`              = "The direction to the nearest town",
        `NEAREST_TOWN`           = "Name of the nearest town",
        `LEASE_DIST`             = "Unused",
        `CONTIG_ACRES`           = "Number of contiguous acres in lease",
        `PERPEN_LEASE_UNIT`      = "Unused",
        `PERPEN_SUR_SEC`         = "Unused",
        `BOT_HOLE_LEASE_UNIT`    = "Unused",
        `BOT_HOLE_SUR_SEC`       = "Unused",
        `P12`                    = "Unused",
        `W1A`                    = "Unused",
        `H2S_AREA`               = "Denotes whether or not H2S gas is present (True/False)",
        `H9`                     = "Unused",
        `MINERAL_RIGHTS`         = "Unused",
        `REMARKS`                = "Unused",
        `FILER_NAME`             = "Unused",
        `FILER_TITLE`            = "Unused",
        `DATE_FILED`             = "Date Permit was filed with the State Agency. If this is not available, then the date the permit was approved is used",
        `PHONE`                  = "Operator's Phone Number",
        `RRC_STAMPED_DATE`       = "Date Permit was filed with the State Agency",
        `ROW_CHANGED_BY`         = "Unused",
        `ROW_CHANGED_DATE`       = "Unused",
        `GRANTED_DATE`           = "Date Permit was Approved",
        `POST_DATE`              = "Date Permit was filed with the State Agency",
        `ASSOC_ID`               = "Unused",
        `ADDR_NO`                = "Unused",
        `DATE_ENTERED`           = "Date Permit was entered into the DI Desktop system",
        `SPUD_DATE`              = "Date Well Began Drilling",
        `LONGITUDE`              = "Longitude of Well (NAD 1927)",
        `LATITUDE`               = "Latitude of Well (NAD 1927)",
        `STATE`                  = "State Abbreviation",
        `PDEN_TYPE`              = "Well Classification (Oil, Gas, CBM, Dry Hole, etc.)",
        `DRILL_TYPE`             = "Well Orientation (Vertical/Horizontal/Directional)",
        `PERMIT_TYPE`            = "Type of work (Original Drill, Workover, Re-Entry, etc…)",
        `LOCATION`               = "Township/Range",
        `SECTION`                = "Section",
        `QTR_QTR`                = "Qtr/Qtr",
        `FTGCOR`                 = "Unused",
        `FTG1`                   = "Surface Location Range Direction (E/W)",
        `FTG1DIR`                = "Surface Location Footage Call 1",
        `FTG2`                   = "Surface Location Footage Call 2",
        `FTG2DIR`                = "Surface Location Footage Call 2 Direction",
        `COUNTY_ID`              = "API County ID",
        `FIELD`                  = "Field well to be drilled in (There may be multiple possibilities which are listed in field1..field5)",
        `RESERVOIR`              = "Formation well to be drilled in (There may be multiple possibilities which are listed in field1..field5)",
        `COMP_DATE`              = "Date well was completed",
        `BASIN`                  = "Basin permit is in",
        `DRILLER`                = "Name of Drilling Company",
        `DRILLER_PHONE`          = "Phone Number of Drilling Company",
        `RIG_NUM`                = "Rig Number",
        `STATUS_DATE`            = "Date of last status change/update loaded in DI Desktop",
        `STATUS`                 = "Well Activity",
        `WELL_DEPTH`             = "Measured Depth",
        `MEAS_DEPTH`             = "Measured Depth",
        `RIG_PRESENT`            = "Indicates if Rig is currently at the location",
        `MAST_ID`                = "Relates to DrillingInfo’s LeaseID",
        `WELL_ID`                = "Relates to DrillingInfo’s WellID",
        `RIG_UPDATE_DATE`        = "Last time rig information was updated for this permit",
        `DATE_PROD`              = "Unused",
        `NEW_WELL`               = "Unused",
        `ORPH_WELL`              = "Unused",
        `LEGAL_SL`               = "Surface Location Legal Description",
        `TWN_SL`                 = "Surface Location Township",
        `TWNDIR_SL`              = "Surface Location Township Direction (N/S)",
        `RNG_SL`                 = "Surface Location Range",
        `RNGDIR_SL`              = "Surface Location Range Direction (E/W)",
        `FTG1REF_SL`             = "Unused",
        `FTG2REF_SL`             = "Unused",
        `QTRSEC_SL`              = "Surface Location Quarter Section",
        `CRTRQD1_SL`             = "Unused",
        `CRTRQD2_SL`             = "Unused",
        `BLKNUM_SL`              = "Surface Location Block Number (Texas)",
        `SRVYNUM_SL`             = "Surface Location Survey Number (Texas)",
        `COUNTY_BH`              = "Bottom Hole Location County",
        `LEGAL_BH`               = "Bottom Hole Location Legal Description",
        `SEC_BH`                 = "Bottom Hole Location Section",
        `TWN_BH`                 = "Bottom Hole Location Township",
        `TWNDIR_BH`              = "Bottom Hole Location Township Direction (N/S)",
        `RNG_BH`                 = "Bottom Hole Location Range",
        `RNGDIR_BH`              = "Bottom Hole Location Range Direction (E/W)",
        `FTG1_BH`                = "Bottom Hole Location Footage Call 1",
        `FTG1DIR_BH`             = "Bottom Hole Location Footage Call 1 Direction",
        `FTG1REF_BH`             = "Unused",
        `FTG2_BH`                = "Bottom Hole Location Footage Call 2",
        `FTG2DIR_BH`             = "Bottom Hole Location Footage Call 2 Direction",
        `FTG2REF_BH`             = "Unused",
        `QTRSEC_BH`              = "Bottom Hole Location Quarter Section",
        `FTGCOR_BH`              = "Unused",
        `CRTRQD1_BH`             = "Unused",
        `CRTRQD2_BH`             = "Unused",
        `ABSTNO_BH`              = "Bottom Hole Location Abstract Number (Texas)",
        `BLKNAM_BH`              = "Bottom Hole Location Block Name (Texas)",
        `BLKNUM_BH`              = "Bottom Hole Location Block Number (Texas)",
        `SRVYNAM_BH`             = "Bottom Hole Location Survey Name (Texas)",
        `SRVYNUM_BH`             = "Bottom Hole Location Survey Number (Texas)",
        `FIELD_1`                = "Field 1 of Well",
        `FORM_1`                 = "Unused",
        `FORM_DEPTH_1`           = "Unused",
        `FIELD_2`                = "Field 2 of Well",
        `FORM_2`                 = "Unused",
        `FORM_DEPTH_2`           = "Unused",
        `FIELD_3`                = "Field 3 of Well",
        `FORM_3`                 = "Unused",
        `FORM_DEPTH_3`           = "Unused",
        `FIELD_4`                = "Field 4 of Well",
        `FORM_4`                 = "Unused",
        `FORM_DEPTH_4`           = "Unused",
        `FIELD_5`                = "Field 5 of Well",
        `FORM_5`                 = "Unused",
        `FORM_DEPTH_5`           = "Unused",
        `FIELD_6`                = "Unused",
        `FORM_6`                 = "Unused",
        `FORM_DEPTH_6`           = "Unused",
        `FIELD_7`                = "Unused",
        `FORM_7`                 = "Unused",
        `FORM_DEPTH_7`           = "Unused",
        `FIELD_8`                = "Unused",
        `FORM_8`                 = "Unused",
        `FORM_DEPTH_8`           = "Unused",
        `WELL_PURP`              = "Unused",
        `JOB_NUM`                = "Unused",
        `WORK_TYPE`              = "Unused",
        `DATE_RELS`              = "Date Rig leaves the location",
        `WELL_PROX`              = "General Proximity of Well to Nearest Town",
        `DRIL_CONT`              = "Unused",
        `DRIL_ADDR`              = "Address of Drilling Company",
        `DRIL_CITY`              = "City of Drilling Company",
        `DRIL_STATE`             = "State Abbreviation of Drilling Company",
        `DRIL_ZIP`               = "Zipcode of Drilling Company",
        `DRIL_TERM`              = "Unused",
        `ADD_INFO`               = "Unused",
        `RECRD_STAT`             = "Unused",
        `WELL_ACTV`              = "Unused",
        `MAP_REF`                = "Unused",
        `OPER_CONT`              = "Unused",
        `APPROVED`               = "Flags whether permit has been approved or is still pending",
        `COMP_EXISTS`            = "Flags if completion data is linked to this permit in DrillingInfo",
        `LATITUDE_EX1`           = "Unused",
        `LONGITUDE_EX1`          = "Unused",
        `IMAGE_PATH`             = "Internal Use"
    )
)